default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_development

test:
  <<: *default
  database: news_test

production:
  <<: *default
  database: news_production
  username: news
  password: <%= ENV['NEWS_DATABASE_PASSWORD'] %>
